name: terraform-tutorials-ci

on: [push, pull_request]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up Terraform
        uses: marocchino/setup-terraform@v1
        with:
          version: "0.11.18"
      - name: Build module 'aws-instance-first-script'
        run: cd aws-instance-first-script && terraform init && terraform validate && terraform plan